### ISSUE TITLE
BUG Apple IPhone 12 Pro Max Display size Problem

### ISSUE THREAD

**Issue by Unkn0wnCreator** [ggerganov/ggmorse#1]
On my iPhone scales the app very bad so that i almost cant press the buttons, because they are behind the notch / clock

**Comment by ggerganov** [comment]
Thanks for the report! Will fix this soon

**Comment by ggerganov** [comment]
This should be fixed in latest GGMorse v1.3.2
Please, let me know if there are any other issues that you observe.

**Comment by Unkn0wnCreator** [comment]
Its fixed.

Thank you :)
