### ISSUE TITLE
Can't scroll the settings dialog.

### ISSUE THREAD

**Issue by FastThenLeft** [ggerganov/ggmorse#6]
Ubuntu 21.04, GGMorse v1.3.4

I can't scroll the settings dialog. Extending the window on my 1920x1080 monitor is just barely long enough to get to the bottom.

I noticed the browser version has the same issue.

BTW, thanks for this app! I LOVE it! I'm doing S&P on the ARRL DX contest with it, and it works perfectly!

**Comment by ggerganov** [comment]
Thanks for the feedback!

Just to make sure - you click on the empty space and drag, correct?
Like so:

https://user-images.githubusercontent.com/1991296/154835079-30cf3ca6-9623-42de-a4aa-7155f464cf33.mov

**Comment by FastThenLeft** [comment]
OK, I feel like a moron. It works. Since I'm running on a desktop I guess I
was looking for a scroll bar. It never occured to me to click and drag. Now
that I see this also runs on a phone, tap and drag makes sense. Sorry for
wasting your time, but thanks again for such a great app! S&P on CW has
never been easier. I might even try running some stations tomorrow.
-David

**Comment by ggerganov** [comment]
No worries! The interface of the app is not very standard, so some of the functionality might not be intuitive.

I'm really glad that you like the app and find it useful.
If you ever have any other feedback or ideas for improvement, please let me know!
73!
